import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
const N=['도','레','미','파','솔','라','시'], F=[261.63,293.66,329.63,349.23,392,440,493.88], S=['메이저','내추럴 마이너','하모닉 마이너'];
type Mode='identify'|'sing'|'scale'|'sequence';
function App(){
 const [mode,setMode]=useState<Mode>('identify'),[target,setTarget]=useState(5),[scale,setScale]=useState(0),[answer,setAnswer]=useState(''),[continuous,setContinuous]=useState(true),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[status,setStatus]=useState('음성 대기 중'),[seq,setSeq]=useState<number[]>([]),[seqAns,setSeqAns]=useState<number[]>([]);
 const next=()=>{setTarget(Math.floor(Math.random()*7));setScale(Math.floor(Math.random()*3));setSeq(Array.from({length:4},()=>Math.floor(Math.random()*7)));setSeqAns([]);setAnswer('');setStatus('음성 대기 중')};
 const tone=(frequency:number,duration=1.2)=>{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=frequency;g.gain.setValueAtTime(.45,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+duration+.1)};
 const play=()=>tone(F[target]); const playScale=()=>[0,2,4,5,7,9,11,12].forEach((x,i)=>setTimeout(()=>tone(F[target]*2**(x/12),.7),i*450)); const playSeq=()=>seq.forEach((n,i)=>setTimeout(()=>tone(F[n],.65),i*750));
 const finish=(ok:boolean,msg:string)=>{setAnswer(msg);setScore(x=>x+(ok?1:0));setStreak(x=>ok?x+1:0);if(ok&&continuous)setTimeout(()=>{const n=Math.floor(Math.random()*7);setTarget(n);setScale(Math.floor(Math.random()*3));setSeq(Array.from({length:4},()=>Math.floor(Math.random()*7)));setSeqAns([]);setAnswer('');setStatus('음성 대기 중');setTimeout(()=>tone(F[n]),180)},1100)};
 const choose=(n:number)=>finish(n===target,n===target?'정답입니다!':`정답은 ${N[target]}`);
 const voice=()=>{const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R){setStatus('Chrome에서 음성 인식을 지원합니다');return}const r=new R();r.lang='ko-KR';r.interimResults=false;setStatus('듣는 중…');r.onresult=(e:any)=>{const t=e.results[0][0].transcript.replace(/\s/g,'');const a=[['도','c','씨'],['레','d','디'],['미','e','이'],['파','f','에프'],['솔','소','g'],['라','a','에이'],['시','b','비']];const n=a.findIndex(x=>x.some(y=>t.includes(y)));n<0?setStatus('음 이름을 인식하지 못했어요'):choose(n)};r.onerror=()=>setStatus('다시 말해 주세요');r.start()};
 const chooseScale=(n:number)=>finish(n===scale,n===scale?'정답입니다!':`정답은 ${S[scale]}`);
 const chooseSeq=(n:number)=>{const a=[...seqAns,n];setSeqAns(a);if(a.length===seq.length)finish(a.every((v,i)=>v===seq[i]),a.every((v,i)=>v===seq[i])?'정답입니다!':'순서가 달라요')};
 return <main><section className="card"><header><div><p className="eyebrow">DAILY PITCH · HANDS FREE</p><h1>음정 연습</h1></div><div className="stats">정답 {score}<br/>연속 {streak}</div></header><label className="continuous"><input type="checkbox" checked={continuous} onChange={e=>setContinuous(e.target.checked)}/><b>연속모드</b><span>판정 후 자동 진행</span></label><nav>{([['identify','음 맞히기'],['sing','따라 부르기'],['scale','스케일'],['sequence','청음']] as [Mode,string][]).map(([m,n])=><button className={mode===m?'active':''} onClick={()=>{setMode(m);next()}} key={m}>{n}</button>)}</nav>
 {mode==='identify'&&<><p className="sub">소리를 듣고 음 이름을 말하거나 선택하세요.</p><button className="listen" onClick={play}>▶ 목표음 듣기</button><button className="voice" onClick={voice}>🎙 음성으로 답하기</button><p className="speech-status">{status}</p><div className="options">{N.map((n,i)=><button onClick={()=>choose(i)} key={n}>{n}</button>)}</div><p className="feedback">{answer}</p></>}
 {mode==='sing'&&<><p className="sub">목표음을 듣고 같은 음을 2초 유지하세요.</p><div className="target"><span>목표음</span><strong>{N[target]}</strong></div><button className="listen" onClick={play}>▶ 목표음 듣기</button><button className="voice" onClick={voice}>🎙 음정 측정 시작</button><p className="speech-status">따라 부르기 판정은 다음 단계에서 연결합니다.</p></>}
 {mode==='scale'&&<><p className="sub">스케일을 듣고 종류를 선택하세요.</p><button className="listen" onClick={playScale}>▶ 스케일 듣기</button><div className="options three">{S.map((s,i)=><button onClick={()=>chooseScale(i)} key={s}>{s}</button>)}</div><p className="feedback">{answer}</p></>}
 {mode==='sequence'&&<><p className="sub">4개의 음을 듣고 순서대로 선택하세요.</p><button className="listen" onClick={playSeq}>▶ 무작위 음 듣기</button><div className="sequence-read">{seqAns.length?seqAns.map(x=>N[x]).join(' - '):'입력 대기 중'}</div><div className="options">{N.map((n,i)=><button onClick={()=>seqAns.length<4&&chooseSeq(i)} key={n}>{n}</button>)}</div><p className="feedback">{answer}</p></>}
 <button className="next" onClick={next}>새 문제 ↻</button></section></main>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
